version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omnibrain-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ./app:/app/app
      - ./database:/app/database
      - ./document_processing:/app/document_processing

  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: omnibrain-frontend
    command: streamlit run frontend/app.py --server.address=0.0.0.0 --server.port=8501
    ports:
      - "8501:8501"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app/frontend
